### ISSUE TITLE
Flux-Infused JetPlate doesn't charge RF items

### ISSUE THREAD

**Issue by MysticalHeat** [CyberdyneCC/SimplyJetpacks-2#138] opened 2019-05-12 07:32 UTC
I'm playing on FTB Presents Direwolf20 1.12.2 modpack and I found a problem with Flux-Infused JetPlate. I enabled jetpack charger but my RF tools don't want to charge. So, another items as flux packs charge items, but JetPlate is not.
![image](https://user-images.githubusercontent.com/48136675/57579161-d776fe80-74a0-11e9-952a-cca0e927e1a0.png)
![Screenshot_4](https://user-images.githubusercontent.com/48136675/57579182-32105a80-74a1-11e9-9b6f-2c03b58c5931.png)

**Comment by Tomson124** [comment] 2019-05-12 09:24
Which version of the modpack are you playing, or more precise which versions of SJ2 are you using?

**Comment by MysticalHeat** [comment] 2019-05-12 09:26
![image](https://user-images.githubusercontent.com/48136675/57580354-13b25b00-74b1-11e9-8e86-891bc80b2b1e.png)
![image](https://user-images.githubusercontent.com/48136675/57580360-2331a400-74b1-11e9-8b06-802eaf44f1a9.png)

**Comment by fishsicles** [comment] 2019-05-20 21:37
I can confirm that this bug also occurs with the Dark Soularium JetPlate and EnderIO muI energy, using SimplyJetpacks2 version 2.2.12.65 (I manually updated from the standard version in FTB Revelation to try and fix this bug) and EnderIO version 5.0.39.

It also doesn't charge Actually Additions tools. In both the EnderIO and Actually Additions cases, the Vibrant Capacitor Pack (Armoured) worked perfectly well, so it's an issue with the JetPlate specifically.

**Comment by Tomson124** [comment] 2019-05-27 16:15
Is fixed in code, will be out with the new version this week.

**Comment by DilithiumNitrate** [comment] 2019-08-13 11:21
This issue hasn't been fixed yet, there have been no new commits since 12 May. Will you commit your bugfix, or even build a new version of this mod, any time soon?

**Comment by Tomson124** [comment] 2019-08-13 21:25
Sorry forgot to publish it. Is now up on Curse.

**Closed as completed by Tomson124** 2019-08-13 21:25 UTC
