### ISSUE TITLE
Crash when connecting to server

### ISSUE THREAD

**Issue by Xiaminou** [CyberdyneCC/SimplyJetpacks-2#82] opened 2018-05-06 12:04 UTC
[crash-2018-05-06_14.02.30-client.txt](https://github.com/Tomson124/SimplyJetpacks-2/files/1977586/crash-2018-05-06_14.02.30-client.txt)

Minecraft: 1.12.2
Forge: 2675
Mods: [list.txt](https://github.com/Tomson124/SimplyJetpacks-2/files/1977587/list.txt)

**Comment by Xiaminou** [comment] 2018-05-06 12:22
Hmm, this might not be SJ, I downgraded to previous version and it still crashes. I don't know what it is.

**Comment by Tomson124** [comment] 2018-05-06 12:33
Try deleting the SJ2 configs on your server and on your client.

**Comment by Bneboy** [comment] 2018-05-06 17:50
Hey,
I get a very similar crash. I followed what you said by deleting the configs, no changes. I crash when I am loading into SP.

https://pastebin.com/D1ZGX0qt
Edit: Forgot paste

**Comment by Tomson124** [comment] 2018-05-06 18:09
Did you try redownloading it, as this seems like a very odd error, cannot reproduce it either.

**Comment by Xiaminou** [comment] 2018-05-06 18:29
From a quick look at your crash report we both have Vanillafix. I tried SJ and Vanillafix, it crashes, removing Vanillafix fixes the problem.

**Comment by Runemoro** [comment] 2018-05-06 20:39
The issue is not caused by VanillaFix. The latest version of VanillaFix causes a crash when a scheduled task throws an exception as a feature to and inform the player that something went wrong rather than silently failing and possibly causing corruption or harder to debug errors later on, and to help mod makers with solving issues that might otherwise never be be found (without vanillafix, it only shows up as a log message).

However, future versions will contain a config option to disable this feature (possibly even allowing resuming the game for all types of crashes)!

**Comment by Curunir** [comment] 2018-05-07 10:04
I am having that very same issue after adding VanillaFix. Crash log for reference: 
[crash-2018-05-07_11.55.50-client.txt](https://github.com/Tomson124/SimplyJetpacks-2/files/1979426/crash-2018-05-07_11.55.50-client.txt)
Facts:
- issue happens upon singleplayer world load, both with an existing world and a fresh one
- issue is not dependent on SJ2 version, downgrade to 2.2.3.33 does not fix it
- deleting SJ2 config files does not change anything
- apparently only happens when VanillaFix is installed alongside SJ2

I will disable VanillaFix as a workaround, but a solution would be most welcome, no matter who has to implement it. Meanwhile, thanks for all the work, everybody.

**Comment by ZombieHDGaming** [comment] 2018-05-10 01:13
@Tomson124 while I do work with Runemoro on VanillaFix, I'd highly suggest you look into your configs and how they do stuff. While VanillaFix should not crash from the task throwing an error (it's a config option now), the mod should not be throwing this on world load:
```java
[21:04:13] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at tonius.simplyjetpacks.item.Jetpack.loadConfig(Jetpack.java:305) ~[Jetpack.class:?]
	at tonius.simplyjetpacks.item.Jetpack.loadAllConfigs(Jetpack.java:230) ~[Jetpack.class:?]
	at tonius.simplyjetpacks.network.message.MessageConfigSync.handleMessage(MessageConfigSync.java:51) ~[MessageConfigSync.class:?]
	at tonius.simplyjetpacks.network.message.MessageConfigSync$1.run(MessageConfigSync.java:42) ~[MessageConfigSync$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 17 more
```
This could lead to even more severe issues, and also, it seems that something is going wrong in your config syncing system. As for what, I'm not sure, but this is definitely an issue that should be addressed eventually.

Sorry if this sounded rude or arrogant in any way, I just wanted to inform you of this in case you didn't know of the issue already.

**Comment by thundr** [comment] 2018-05-30 06:48
This should be fixed with the recent changes to config, please reopen if not.

**Closed as completed by thundr** 2018-05-30 06:48 UTC
Labels: Need more Information
