### ISSUE TITLE
[1.12.2]

### ISSUE THREAD

**Issue by Bass2style** [CyberdyneCC/SimplyJetpacks-2#56] opened 2018-01-22 15:52 UTC
Hi,

i'm running latest Direwolf20 that includes Version 2.2.1.20 of SimplyJetpacks.
i have an issue to craft the armored flux packs.
both reinforced and resonant armored Fluxpacks requires, an armored fluxpack (armored) to be crafted, and no other recipe seems available.
i tryed to "armor" like the T4 jetpack, but it's not working.

i've missed something, or is this a bug ?

Screenshots : 

![fluxpack 1](https://user-images.githubusercontent.com/29619787/35230062-5236e1a8-ff95-11e7-889c-2b3f39f00766.png)
![fluxpack 2](https://user-images.githubusercontent.com/29619787/35230064-524f77d6-ff95-11e7-994c-b382d60f0567.png)

B2S

**Comment by Tomson124** [comment] 2018-01-22 20:54
Duplicate of #49

**Closed as completed by Tomson124** 2018-01-22 20:54 UTC
Labels: duplicate
