### ISSUE TITLE
Doesn't work with modular EnderIO on Minecraft 1.12.2

### ISSUE THREAD

**Issue by arcriley** [CyberdyneCC/SimplyJetpacks-2#64] opened 2018-03-13 18:12 UTC
I have EnderIO installed in the new modular format with the following modules;
 EnderCore-1.12.2-0.5.16.jar
 EnderIO-base-1.12.2-5.0.241-nightly.jar
 EnderIO-conduits-1.12.2-5.0.241-nightly.jar
 EnderIO-integration-tic-1.12.2-5.0.241-nightly.jar
 EnderIO-invpanel-1.12.2-5.0.241-nightly.jar
 EnderIO-machines-1.12.2-5.0.241-nightly.jar

SimplyJetpacks2 says it requires Thermal Expansion, indicating that it didn't detect EnderIO installed.

**Comment by liquidblur** [comment] 2018-03-13 19:20
When this has already been talked about in the EIO discord, and known that EIO API isnt fully finished and still in pre-alpha; also knowing there is currently a work around to solving this. Don't expect a fix from SumplyJetpacks till EIO is out of Dev/pre-alpha and the API is built 


install EIO modularly and remove the forestry integration, this should solve your issue you are having

**Comment by arcriley** [comment] 2018-03-13 23:46
As you can see from the above list of modules, I do have EnderIO installed modularly and without forestry integration. I do have tinkers construct integration, though.

**Comment by liquidblur** [comment] 2018-03-14 00:25
it shouldn't matter about tinkers integration, something else is triggering this error as I'm running SimplyJetpacks2 and EIO/Forestry sidebyside without thermal

**Comment by arcriley** [comment] 2018-03-14 00:32
Here is the full list;

'BiblioCraft[v2.4.3][MC1.12.0].jar'
 Biome_Bundle-1.12.2-v6.1.jar
 cucumber-1.12-1.0.4.jar
 EnderCore-1.12.2-0.5.16.jar
 EnderIO-base-1.12.2-5.0.242-nightly.jar
 EnderIO-conduits-1.12.2-5.0.242-nightly.jar
 EnderIO-integration-tic-1.12.2-5.0.242-nightly.jar
 EnderIO-invpanel-1.12.2-5.0.242-nightly.jar
 EnderIO-machines-1.12.2-5.0.242-nightly.jar
 Hwyla-1.8.23-B38_1.12.jar
 jei_1.12.2-4.8.5.159.jar
 Mantle-1.12-1.3.1.21.jar
 mysticalagriculture-1.12-1.6.8.jar
 OpenTerrainGenerator-1.12.2+-+v5.jar
 OptiFine_1.12.2_HD_U_C9.jar
 SimplyJetpacks2-1.12.2-2.2.2.28.jar
 TConstruct-1.12.2-2.9.1.65.jar
​

**Comment by liquidblur** [comment] 2018-03-14 00:35
# When enabled, Simply Jetpacks will register its Thermal Expansion-based jetpacks and flux packs.
    B:"ThermalExpansion integration"=false

    # When enabled, Simply Jetpacks will register its Ender IO-based jetpacks and flux packs.
    B:"Ender IO integration"=false

make these false

also again until EnderIO API is stable and done don't expect any mod to really function right with them as they were shipped with an oldass api

**Comment by arcriley** [comment] 2018-03-14 00:49
Usually the first step in "installing" a mod is running Minecraft once so
that its default config gets added to config/ -  then I can close Minecraft
and edit the configs as needed. However, this error comes up before before
the config file is created so I have nothing to edit.

Removing all the Ender* mods doesn't fix this problem.

**Comment by Tomson124** [comment] 2018-04-06 06:55
The problem is, I am still depending on the RF API as there was no EnderIO when I did the port. So TE is a hardcoded dependency in the latest version. This means minecraft will not load the mod until you add it as an dependency. This will be fixed as soon as an offical beta or release version of EnderIO is out and their API is mostly finished. (Don't want to redo the integration everytime because they change their API again...)

**Comment by arcriley** [comment] 2018-04-06 07:25
Enderio is released now...

**Comment by Dhvagra** [comment] 2018-05-09 12:46
EnderIO 5 has been out for over a month now, and the API is robust as far as I hear. Have you made any progress? Or has real life been hogging your time? ;)

**Comment by Tomson124** [comment] 2018-05-09 13:42
I know but there are currently 2 things hloding me back. First of all there are some really weird bugs in the mod currently which I don't know (yet) how to fix. Secondly their are currently no maven deobf builds for EnderIO which means I can not integrate it automatically into my project so I have to look up every bit of code manually which is very time consuming and frustrating. Tey told me they add this soon. And yeah personal life is a little in the way, too and my new found "addiction" to Fortnite :D But I am working on the mod more latley as since the breakup this is kind of distracts me from it and... well there is more time now ^^

**Comment by thundr** [comment] 2018-05-24 23:28
This is fixed with #92

**Comment by thundr** [comment] 2018-05-26 19:49
Merged, please reopen if there are more problems with EIO

**Closed as completed by thundr** 2018-05-26 19:49 UTC
Labels: enhancement
