### ISSUE TITLE
Client tweaks override configs from server

### ISSUE THREAD

**Issue by jc2xs** [CyberdyneCC/SimplyJetpacks-2#55] opened 2018-01-15 22:39 UTC
A client connected to a server can go into the settings for Simply Jetpacks and tweak the speed and fuel usage settings.  These will actually take precedence over the server configs for the mod.  This shouldn't be allowed behavior.  They do this in game by pressing ESC then clicking on mod options, find Simply Jetpacks in the list and then tweak the settings for the tier jetpack they are using.

Simply Jetpacks2 version 2.2.1.20
Forge: 14.23.1.2583

**Comment by Tomson124** [comment] 2018-02-19 19:34
I finally had some spare time and started coding again. I just pushed some code which maybe could fix the issue. Quite new to the network system of minecraft...
As I don't have much time for testing (or coding) at the moment and no server or persons to help me either, would you be so kind and test it? There is a build #29 on jenkins (http://modmuss50.me:8080/job/SimplyJetpacks-2/job/SimplyJetpacks-2-1.12/) which includes the "maybe" fix.
Please let me know if it helps. I did this fix only for Jetpacks now, so no need to test Fluxpacks.
You are also invited to join my discord (link in the repo's readme) so we can talk about this more directly.

**Comment by poeticbulldozer** [comment] 2018-02-20 00:02
I intended to test the fix for Tomson124, but I am unable to replicate the bug in either the current version of simply jetpacks 2 or the version listed in the bug report. I've even downloaded the specific pack referenced earlier in the report and started a server in hopes of getting the bug there. No dice. What are the circumstances under which this bug can be reproduced?

**Comment by jc2xs** [comment] 2018-02-20 03:07
After you start the server and you are connected and in game, press the ESC key then go into the mod options find simply jetpack and change the settings for the tier of jet pack you have.  In my case the testing was done with the tier 3.  But you can adjust the client side settings for fuel usage, speed, etc.  When you exit the options screen and return to the game you have in session you will see those client side setting you just changed actually override the server.  Easiest things to test is things like hover and speed.  Like you shouldn't be able to get creative hover on a T3 jetpack.  But modifying the configs after you connect to the server you can.

**Comment by Tomson124** [comment] 2018-02-25 21:28
Any news on the testing guys?

**Comment by poeticbulldozer** [comment] 2018-02-25 22:33
I was unfortunately unable to replicate this under any circumstances on any version of simply jetpacks 2. It's gonna have to be jc2xs who follows up on this one. Sorry!

**Comment by thundr** [comment] 2018-06-28 00:11
This was fixed with recent config refactors. If this is still reproducible, please reopen.

**Closed as completed** 2018-06-28 00:11 UTC
Labels: bug, Need more Information
